### PR TITLE
86: Better RSS proxy error handling

### LINKED ISSUE #86: Better error handling and messaging for embeds using bad feed URL's
We are seeing a lot of embed requests using feed URL's are inaccessible (404, Bad DNS, SSL issues, etc.). These embeds were probably already broken with the Angular player, but those requests were happening on the client, so I am not sure if we were aware of those error (New Relic?)

Right now we are just throwing an error when fetching of RSS feed fails, which just ends up showing a generic error message. We should probably handle these errors a little better, and present something a bit more informative to the user viewing the embed.

### PR DESCRIPTION
**Pull request by rpeterman-gp**
Closes #86 

- rss proxy errors return 400 response
- show error message for bad feed URL's
- add same error handling and messaging to listen page

## To Review

- [ ] Checkout Branch.
- [ ] Run `asdf install`.
- [ ] Run `yarn`.
- [ ] Run `yarn dev`.
- [ ] Go to http://localhost:4300/e?uf=https://google.com.

> ...then...

- [ ] Ensure error message is shown.
- [ ] Ensure document responds with a 400 status code.
- [ ] Ensure the same occurs for RSS landing pages: http://localhost:4300/listen?uf=https://google.com

### CODE REVIEW

File: interfaces/error/IPageError.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+/**
+ * Defines interfaces for page errors.
+ */
+
+export interface IPageError {
+  statusCode: number;
```
Comment (cavis) [inline interfaces/error/IPageError.ts:6]: What do you use here for non-http errors?  Bad dns, invalid url, invalid scheme, etc.

**Review by cavis — APPROVED** [review]
I guess the only downside I see is that we don't tell the user exactly _why_ the url was invalid.  (At least not in the case of DNS, non-urls, etc).

But then again, in prod that's not actually important.

👍 onwards!

File: interfaces/error/IPageError.ts (hunk 1 above)
Comment (rpeterman-gp) [reply interfaces/error/IPageError.ts:6]: My thought here is these codes are for the page being requested, so http status codes seemed like those that would like need to be used here.
