### PR TITLE
113: Parse multiple podcast value

### LINKED ISSUE #113: RSS feed with multiple `podcast:value` tags not working for web monetization
https://play.prx.org/e?uf=https://podnews.net/rss

I suspect the issue is which comes first - can we update the code to handle multiple value tags in the feed, and look for one that matched `ILP` and `webmonetization`?

### PR DESCRIPTION
**Pull request by rpeterman-gp**
Closes #113

- Filter `podcast:value` items to first item with `type = 'webmonetization'` and `method = 'ILP'`, then use that in parsed feed data.
- fixes a bug where images from a a third party server would not un-blur when loaded.

## To Review

- [ ] Use the preview deployment: LINK_HERE

> ...or...

- [ ] Checkout Branch.
- [ ] Run `asdf install`.
- [ ] Run `yarn`.
- [ ] Run `yarn dev`.
- [ ] Go to http://localhost:4300/api/proxy/rss?u=https://podnews.net/rss.

> ...then...

- [ ] Ensure `podcast` prop is in root object and contains the data for the correct `podcast:value` node.
- [ ] Go to http://localhost:4300/e?uf=https://podnews.net/rss
- [ ] Ensure web monetization icon is shown next to progress bar.
- [ ] Ensure thumbnail doesn't remain blurred after it loads.
- [ ] Run `yarn test` and completes without error.

### CODE REVIEW

File: lib/fetch/rss/fetchRssFeed.ts [hunk 1]
```diff
@@ -11,7 +11,11 @@ type CustomItem = {
 
 const parser: Parser<CustomFeed, CustomItem> = new Parser({
   customFields: {
-    feed: ['podcast:value', 'itunes:type'],
+    feed: [
+      // @ts-ignore
+      ['podcast:value', 'podcast:value', { keepArray: true }],
```
Comment (kookster) [inline lib/fetch/rss/fetchRssFeed.ts:16]: `keepArray`! that's a good option, didn't know about that one...

**Review by kookster — APPROVED** [review]
lgtm!

File: lib/fetch/rss/fetchRssFeed.ts (hunk 1 above)
Comment (rpeterman-gp) [reply lib/fetch/rss/fetchRssFeed.ts:16]: Had to dig deep in the docs to find it.
