### PR TITLE
Fixed div tag

### LINKED ISSUE #109: Close div tag on responsive card example
https://github.com/PRX/Play-Next.js/blob/main/pages/index.tsx#L294

Should be `</div>`

### PR DESCRIPTION
**Pull request by a-maci29**
Closes #109

### CODE REVIEW

File: pages/index.tsx [hunk 1]
```diff
@@ -307,7 +307,7 @@ const Home: NextPage = () => {
     href="...&ca=1"
     style="position: absolute; inset: 0;"
   />
-</div>`}
+</div>}
```
Comment (kookster) [inline pages/index.tsx:310]: The line was #294 https://github.com/PRX/Play-Next.js/pull/110/files#diff-aa98fd0757d0e1741503c50cfafb7726939d19819638bbe8e030a27adfec34a3R294

Where there is a:
```
<div>`}
```

that should be:
```
</div>`}
```

**Review by kookster — CHANGES_REQUESTED** [review]
I think that's the wrong line.

**Review by kookster — APPROVED** [review]
lgtm
