### PR TITLE
159: Update SRT transcript detection to include `application/x-subrip` content type

### LINKED ISSUE #159: rss.com hosted feeds with transcript tag not showing cc / transcript UI
Doesn't work, has SRT transcript
https://play.prx.org/listen?uf=https://media.rss.com/james-cridland/feed.xml

also errors in the console:
```
framework-2c16ac744b6cdea6.js:9 Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at rh (framework-2c16ac744b6cdea6.js:9:40161)
    at framework-2c16ac744b6cdea6.js:9:100672
    at oI (framework-2c16ac744b6cdea6.js:9:106183)
    at oD (framework-2c16ac744b6cdea6.js:9:99131)
    at framework-2c16ac744b6cdea6.js:9:98938
    at oO (framework-2c16ac744b6cdea6.js:9:98945)
    at ox (framework-2c16ac744b6cdea6.js:9:93984)
    at x (framework-2c16ac744b6cdea6.js:33:1364)
    at MessagePort.T (framework-2c16ac744b6cdea6.js:33:1894)
188framework-2c16ac744b6cdea6.js:9 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lg (framework-2c16ac744b6cdea6.js:9:46457)
    at i (framework-2c16ac744b6cdea6.js:9:121104)
    at oD (framework-2c16ac744b6cdea6.js:9:99071)
    at framework-2c16ac744b6cdea6.js:9:98938
    at oO (framework-2c16ac744b6cdea6.js:9:98945)
    at ox (framework-2c16ac744b6cdea6.js:9:93984)
    at x (framework-2c16ac744b6cdea6.js:33:1364)
    at MessagePort.T (framework-2c16ac744b6cdea6.js:33:1894)
framework-2c16ac744b6cdea6.js:9 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (framework-2c16ac744b6cdea6.js:9:120773)
    at oD (framework-2c16ac744b6cdea6.js:9:99071)
    at framework-2c16ac744b6cdea6.js:9:98938
    at oO (framework-2c16ac744b6cdea6.js:9:98945)
    at oE (framework-2c16ac744b6cdea6.js:9:95697)
    at ox (framework-2c16ac744b6cdea6.js:9:94252)
    at x (framework-2c16ac744b6cdea6.js:33:1364)
    at MessagePort.T (framework-2c16ac744b6cdea6.js:33:1894)
```

### PR DESCRIPTION
**Pull request by rpeterman-gp**
Closes #159 

- add `x-subrip` to srt detection in transcript proxy
- add `x-subrip` to srt conversion check in Player

## To Review

- [ ] Use the preview deployment: LINK_HERE

> ...or...

- [ ] Checkout Branch.
- [ ] Run `asdf install`.
- [ ] Run `yarn`.
- [ ] Run `yarn dev`.
- [ ] Go to http://localhost:4300/listen?uf=https%3A%2F%2Fmedia.rss.com%2Fjames-cridland%2Ffeed.xml

> ...then...

- [ ] Ensure CC buttons are shown and function as expected.
- [ ] Repeat for http://localhost:4300/e?uf=https%3A%2F%2Fmedia.rss.com%2Fjames-cridland%2Ffeed.xml

### CODE REVIEW

File: components/Player/Player.tsx [hunk 1]
```diff
@@ -58,7 +58,7 @@ const Player: React.FC<IPlayerProps> = ({
   const { url, previewUrl, transcripts, duration } = currentTrack;
   const currentTrackUrl = previewUrl || url;
   const transcript = transcripts?.find(
-    (t) => !!['vtt', 'srt', 'json'].find((n) => t.type.includes(n))
+    (t) => !!['vtt', 'srt', 'x-subrip', 'json'].find((n) => t.type.includes(n))
```
Comment (kookster) [inline components/Player/Player.tsx:61]: looks good - the docs have these as options:
https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#attributes
```ext/plain, text/html, text/vtt, application/json, application/x-subrip```
So looking for subrip and srt is good!

**Review by kookster — APPROVED** [review]
lgtm!
